### ISSUE TITLE
Keyboard Navigation bugs

### ISSUE THREAD

**Issue by TheMarit** [joffreyBerrier/vue-spreadsheet#194]
1.) If you focused on an input cell, so you are editing it. It would be very helpful if the arrow keys would not move cells but would move the cursor within your field. 

2.) Same with the backspace/delete key. If you just have it selected and hit delete it deletes the entire value which is great, but if you are focused on it and actively editing, it would be very helpful if it would just remove 1 letter, like when you are normally using the keyboard.

3.) If you accidentally delete something and hit command/ctrl + z it undo's the changes which is great, but it doesn't fire the tbody-change-data event. This is giving me issues since I'm updating my database on tbody-change-data event. When I delete something, it deletes it in my db, then I hit command + z, it looks like it is back, but it isn't in my db, because the event didn't get fired.

4.) If you hit delete on a disabled cell, you can still delete the value. I don't think that should be possible.

Please let me know if you have any questions/issues reproducing this.

**Comment by joffreyBerrier** [comment]
Hi @TheMarit it's very clear,

I will take time to resolve the problem, I will inform you when it is resolved!

thx

**Comment by TheMarit** [comment]
@joffreyBerrier As of 1. and 2. I've created a pull request that I think should resolve the issue. 

for nr 3. I could resolve this myself once I dived into the code I found tbody-undo-data I missed that in the documentation.

**Comment by joffreyBerrier** [comment]
@TheMarit , cool for the nr 3 !
Do you think my documentation need to be improved ? If you want to help me to improve it, do not hesitate :)

I have comment your request

**Comment by joffreyBerrier** [comment]
@TheMarit Release on 2.0.0 thx for help !
