### ISSUE TITLE
Can we implement validations on the data entered in cells?

### ISSUE THREAD

**Issue by shivm12** [joffreyBerrier/vue-spreadsheet#199]
I want to validate the data whether the user has entered correct data or not in the cell.
For example : If in cell if user wants to enter the alphabets then there must be some validation to stop user from entering the alphabets as that cell can only take numeric values. 
So how to implement these validations on cell?

**Comment by joffreyBerrier** [comment]
Hi @shivm12 

You can trigger the `@change` event on the textarea like this:

`@tbody-change-data="changeData"`

This function gives you two params: `rowIndex, header`

Add a key `numeric` with a `boolean` in your object

Example:

```
products: [
...
h: {
  type: "input",
  value: "value",
  numeric: true,
  style: { color: "#000"}
},
]
```

Then in the changeData function you can do:

```
if (data[rowIndex][header].numeric === true) {
  // your function
}
```

I hope it's answering your question

thx

**Comment by shivm12** [comment]
Hi @joffreyBerrier ,
Thanks for the response, but this will not solve my problem i want to disable the alphabet keys of the keyboard so that user can only enter numeric values.

**Comment by joffreyBerrier** [comment]
Hi @shivm12,

I understand the problem, I will try to add a new param on the input object to disable or enable alphabet

I will inform you when it's ok

thx

**Comment by joffreyBerrier** [comment]
@shivm12 it's live !

add numeric to true on your object like this:

```javascript
data: [
    {
      c: {
        type: "input",
        numeric: true,
        value: "1234567890",
        style: {
          color: "#000",
        },
      },
...
]
```
