### ISSUE TITLE
[BUG] When "handleSearch" enabled, double click should not open an empty cell

### ISSUE THREAD

**Issue by Kapcash** [joffreyBerrier/vue-spreadsheet#204]
**Describe the bug**
When a cell is declared as a `<select>`, using `handleSearch` property, the double click don't open the select but focus on an empty cell.

**To Reproduce**
1. Declare some cells as selects with `handleSearch: true`
2. Add some `selectOptions` in it.
3. Check that the cell really is a select with a list when single clicking it
4. Double click on the cell -> it opens a blank cell

**Expected behavior**
Double click should not trigger anything but the select.

**Screenshots**
![select-double-click](https://user-images.githubusercontent.com/10612835/86939721-3a663300-c142-11ea-899b-fe0ab535f180.gif)

**Comment by joffreyBerrier** [comment]
🤯 Did you have a solution to correct this ?

**Comment by Kapcash** [comment]
I think I see a solution yes! I'll make a PR later for that :)

Editing the `handleTbodyTdDoubleClick` method with a pre-condition on the `handleSearch` attribute should do the trick.
