### ISSUE TITLE
[BUG] Why indexing 'dist/' in github?

### ISSUE THREAD

**Issue by Kapcash** [joffreyBerrier/vue-spreadsheet#206]
**Describe the bug**
I'm not sure that the `dist/` folder should be indexed on the git repository.
It can lead to merge conflicts easily and if we don't run a build before committing, we have a gap between the sources and the built files.

The dist/ should only be generated locally when publishing to npm in my opinion!

**Comment by joffreyBerrier** [comment]
I delete the `dist` folder :)
