### ISSUE TITLE
[FEATURE_REQUEST]: Vue-spreadsheet on Vue3

### ISSUE THREAD

**Issue by joffreyBerrier** [joffreyBerrier/vue-spreadsheet#214]
Refacto the core on Vue3

**Comment by ewoudwerkman** [comment]
any progress so far on moving to Vue3?

**Comment by joffreyBerrier** [comment]
https://github.com/joffreyBerrier/vue-datepicker

**Comment by shayneoneill** [comment]
Whats the relationship of the datepicker to the spreadsheet?
